### ISSUE TITLE
Comma and Decimal Swap

### ISSUE THREAD

**Issue by pbchristensen** [RSZ-Nld/VFO-1.8-Inch-Retro-scale#1]
How can the comma (,) and decimal (.) be swapped on the frequency display?  Example: 7,050.00 MHz

**Comment by pbchristensen** [comment]
Solution found:

   //-------- Display Digital Frequency ---------------------------------------           
        sprintf(str, "%3d,%03d.%02d",  frq/1000000, (frq/1000)%1000, (frq/10)%100 );

**Comment by RSZ-Nld** [comment]
Great, the sketch is not from me, i only made my own pcb with sketch and somevadjust to it.
But fune that you have a solution!!
