### ISSUE TITLE
idea

### ISSUE THREAD

**Issue by patapirana** [RSZ-Nld/VFO-1.8-Inch-Retro-scale#2]
I made this project and I want to use it in my qrp but I have a problem like entering offset is a big problem for me because I don't know coding :) I think it would be much more useful to create a shortcut for it (like a small offset shift menu when holding any key at boot) ) so that the project will be more useful, is there a way to do this? I think we can solve this by adding such a little code to the existing software

note: sorry for my bad english i use google translate

**Comment by RSZ-Nld** [comment]
Hello I did not made the sketch,  so i can not add something like that.
But you can edit the file for the offset. What is needed for youre offset?

**Comment by patapirana** [comment]
I want to use it in various QRP projects, it is not very useful as it is.

Android için Outlook<https://aka.ms/AAb9ysg> edinin
________________________________

**Comment by RSZ-Nld** [comment]
Yes i know sorry, but it is like how the maker has made this.
I am not good in programming
