### ISSUE TITLE
Compillation error

### ISSUE THREAD

**Issue by Sergey-R5AU** [RSZ-Nld/VFO-1.8-Inch-Retro-scale#3]
I have tried to upload  sketch 

however retrieved errors with memory allocation:

c:/users/r5au/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: C:\Users\r5au\AppData\Local\Temp\arduino\sketches\00AC865E56CF665CC51767B4214E41CF/VFO_ESP32-20-Mem.ino.elf section `.dram0.bss' will not fit in region `dram0_0_seg'
c:/users/r5au/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: DRAM segment data does not fit.
c:/users/r5au/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: DRAM segment data does not fit.
c:/users/r5au/appdata/local/arduino15/packages/esp32/tools/xtensa-esp32-elf-gcc/esp-2021r2-patch5-8.4.0/bin/../lib/gcc/xtensa-esp32-elf/8.4.0/../../../../xtensa-esp32-elf/bin/ld.exe: region `dram0_0_seg' overflowed by 3536 bytes
collect2.exe: error: ld returned 1 exit status

exit status 1

Compilation error: exit status 1

something wrong in the sketch ?

**Comment by RSZ-Nld** [comment]
Sketch is not from me, but you can try to use V2.03 library the esp32. 

And otherwise my bin files are working. So please upload one of these bin files.

**Comment by Sergey-R5AU** [comment]
Thank you for you quick reply, well i`ll try with v2.03 and report after.

Bin files uploading without issues 
Sketch i am using for further modification of
  int32_t offset_frq = 0;    // Offset Frequency[Hz]in + o in - per oscillatore locale LO
  int32_t    car_frq = 0;   // 19000000 frequenza BFO  calcolare + o - 1500 Hz per usb o lsb  // Carrier Frequency[Hz]

after  final LO measure.
So i`ll try tomorrow with reply here

**Comment by RSZ-Nld** [comment]
Yes the ino file can be tricky without the good libraries. 
Therefore i made some flash files. 

Hope it will work for you with v2.03
I know it cost me weeks before i had it worked.

**Comment by Sergey-R5AU** [comment]
Got it, that true, sometime "know how" extremely save a time

**Comment by Sergey-R5AU** [comment]
Have to saved time and returned to monitor, you know...:

you are completely right master !
with library 2.03 sketch compiled and uploaded without errors

Thank you for "know how" !

**Comment by RSZ-Nld** [comment]
Great to hear that, good luck with your project!!

**Comment by Sergey-R5AU** [comment]
![sc](https://github.com/RSZ-Nld/VFO-1.8-Inch-Retro-scale/assets/85807500/48b2d1f8-6963-4ff4-8e16-f889d70d796f)

Done

**Comment by RSZ-Nld** [comment]
Great !!
